User.create(email: "Ruby@horse.net", name: "Ruby Walsh", password: "iLuvIreland")
User.create(email: "Bill@horse.net", name: "Bill Shoemaker", password: "iLuvHorses")
User.create(email: "Mildred@horse.net", name: "Mildred Janowitz", password: "iLuvAQH")
User.create(email: "Valentina@horse.net", name: "Valentina Truppa", password: "iLuvDressage")

Horse.create(name: "Aristides", sex: "Stallion", color: "Chestnut", breed: "Thoroughbred", user_id: 1)
Horse.create(name: "Black Caviar", sex: "Mare", color: "Bay", breed: "Thoroughbred", user_id: 2)
Horse.create(name: "Carbine", sex: "Stallion", color: "Bay", breed: "Thoroughbred", user_id: 3)
Horse.create(name: "Desert Orchid", sex: "Gelding", color: "Gray", breed: "Thoroughbred", user_id: 4)
Horse.create(name: "Eight Belles", sex: "Mare", color: "Gray", breed: "Thoroughbred", user_id: 1)
Horse.create(name: "Frankel", sex: "Stallion", color: "Bay", breed: "Thoroughbred", user_id: 2)
Horse.create(name: "Go Man Go", sex: "Stallion", color: "Roan", breed: "American Quarter Horse", user_id: 3)
Horse.create(name: "Hambletonian 10", sex: "Stallion", color: "Bay", breed: "Standardbred", user_id: 4)
Horse.create(name: "Irish War Cry", sex: "Stallion", color: "Chestnut", breed: "Thoroughbred", user_id: 1)
Horse.create(name: "John Henry", sex: "Gelding", color: "Brown", breed: "Thoroughbred", user_id: 2)
Horse.create(name: "Kelso", sex: "Gelding", color: "Bay", breed: "Thoroughbred", user_id: 3)
Horse.create(name: "La Troienne", sex: "Mare", color: "Bay", breed: "Thoroughbred", user_id: 4)
Horse.create(name: "Man o' War", sex: "Stallion", color: "Chestnut", breed: "Thoroughbred", user_id: 1)
Horse.create(name: "Niatross", sex: "Stallion", color: "Bay", breed: "Standardbred", user_id: 2)
Horse.create(name: "Orfevre", sex: "Stallion", color: "Chestnut", breed: "Thoroughbred", user_id: 3)
Horse.create(name: "Regret", sex: "Mare", color: "Chestnut", breed: "Thoroughbred", user_id: 4)
Horse.create(name: "Seabiscuit", sex: "Stallion", color: "Bay", breed: "Thoroughbred", user_id: 1)
Horse.create(name: "Two Lea", sex: "Mare", color: "Bay", breed: "Thoroughbred", user_id: 2)
Horse.create(name: "Marengo", sex: "Stallion", color: "Gray", breed: "Arabian", user_id: 3)
Horse.create(name: "Strolling Jim", sex: "Gelding", color: "Chestnut", breed: "Tennessee Walking Horse", user_id: 4)
